#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/mnt/pns/home/schneiderm/anaconda3/envs/phy2/Neuron/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/schneiderm/anaconda3/envs/phy2/Neuron/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/mnt/hpx/home/schneiderm/Projects/12_Neuron/hoc_functions/x86_64/.libs/libnrnmech.so" "$@"
