#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/mnt/pns/home/schneiderm/.local/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/gs/home/schneiderm/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/mnt/hpc/home/schneiderm/Projects/12B_Neuron/CellModels/472451419/modfiles/x86_64/.libs/libnrnmech.so" "$@"
